###ansykut github
POST https://dummyjson.com/products/add
Content-Type: application/json

{
  "id": 101,
  "title": "Pumpkin",
  "price": "3.56"
}

###
http://localhost:3000


/////////////////////////
// Products

###
http://localhost:3000/api/v1/products

###
POST http://localhost:3000/api/v1/products/seed

###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "title": "Pumpkin",
  "price": "3.56"
}

###
PATCH http://localhost:3000/api/v1/products/31
Content-Type: application/json

{
  "title": "Pumpkin Spice Latte",
  "price": "6.56"
}

###
DELETE http://localhost:3000/api/v1/products/31


###
https://newpaltz-fall-2023.onrender.com/api/v1/products/28


/////////////////////////
// Users

###
http://localhost:3000/api/v1/users/656de2a5d48fbe3bde0ff2a8

###
POST http://localhost:3000/api/v1/users/
Content-Type: application/json

{
  
  "email": "plotkinm@newpaltz.edu",
    "password": "12345678",
    "isAdmin": true,
     "FirstName": "Jeff",
    "LastName": "jeffsaia",
    "workouts": [
    {
      "lat": "12",
      "long": "2",
      "date": "11/10/2023",
      "speed": 2
    }
  ]
    
}

###
PATCH http://localhost:3000/api/v1/users/656b5db554351df4fad1f584
Content-Type: application/json

{
  "FirstName":"Jeff",
  "LastName":"jeffffffery",
  "workouts":[{
    "distance": 124,
    "time":12
  }]
}

###
DELETE http://localhost:3000/api/v1/users/6568b886973d2029da173d9c

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "email": "TestingAdmin1@newpaltz.edu",
  "password": "12345678",
  "isAdmin": true
}

###
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
  "email": "TestingAdmin1@newpaltz.edu",
  "password": "12345678"
  
}

###
PATCH   http://localhost:3000/api/v1/users/656de73f95df8dd474b00f4a

Content-Type: application/json

{
  

 "workouts": [
    {
      "lat": "12",
      "long": "2",
      "date": "11/10/2023",
      "speed": 2
    }
  ]
 }
  

