###ansykut github
POST https://dummyjson.com/products/add
Content-Type: application/json

{
  "id": 101,
  "title": "Pumpkin",
  "price": "3.56"
}

###
http://localhost:3000


/////////////////////////
// Products

###
http://localhost:3000/api/v1/users

###
POST http://localhost:3000/api/v1/products/seed

###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "title": "Pumpkin",
  "price": "3.56"
}

###
PATCH http://localhost:3000/api/v1/products/31
Content-Type: application/json

{
  "title": "Pumpkin Spice Latte",
  "price": "6.56"
}

###
DELETE http://localhost:3000/api/v1/products/31


###
https://newpaltz-fall-2023.onrender.com/api/v1/products/28


/////////////////////////
// Users

###
http://localhost:3000/api/v1/users/

###
POST http://localhost:3000/api/v1/users/
Content-Type: application/json

{

 "email": "TestingAdmin1@newpaltz.edu",
      "password": "12345678",
      "isAdmin": true,
      "FirstName": "Jeff",
      "LastName": "jeffffffery",
      "friends": [
        "656de73f95df8dd474b00f4a",
        "6570e20962778001b479e4cc"
      ],
      "workouts":[{}]
    }
    


###
PATCH http://localhost:3000/api/v1/users/
Content-Type: application/json

{
  "email": "TestingAdmin@newpaltz.edu",
  "friends":[]
}

###
DELETE http://localhost:3000/api/v1/users/6570e20962778001b479e4cc

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "email": "TestingAdmin1@newpaltz.edu",
  "password": "12345678",
  "isAdmin": true
}

###
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
  "email": "TestingAdmin@newpaltz.edu",
  "password": "12345678"
  
}

###
PATCH   http://localhost:3000/api/v1/users/656de2a5d48fbe3bde0ff2a8

Content-Type: application/json

{
  

 "friends": ["6570e20962778001b479e4cc"]
  
 }
  

