
/////////////////////////
// Users

###
POST http://localhost:3000/api/v1/friends/search
Content-Type: application/json

{
  "email":"testingtheusers@newpaltz.edu"
}
###
POST  http://localhost:3000/api/v1/users/
Content-Type: application/json

{

 "email": "testAuser@newpaltz.edu",
      "password": "12345678",
      "isAdmin": true,
      "FirstName": "Jeff",
      "LastName": "jeffffffery",
      "friends": [
        "656de73f95df8dd474b00f4a",
        "6570e20962778001b479e4cc"
      ],
      "workouts": [
        {
          "id": 0.0633,
          "Distance": 1,
          "Lat": "100",
          "Long": "100",
          "speed": 60,
          "date": "100",
          "time": "1"
        }
      ],
      "userFriends":[{}]

    }
    


###
PATCH http://localhost:3000/api/v1/users/65716227564d8f751deaa496
Content-Type: application/json

{
  "isAdmin": false
 
}

###
DELETE http://localhost:3000/api/v1/users/65716414ffe992dced6d63d5

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
 "email": "testingtheusers@newpaltz.edu",
      "password": "12345678",
      "isAdmin": true,
      "FirstName": "Jeff",
      "LastName": "jeffffffery",
      "friends": [
        "656de73f95df8dd474b00f4a",
        "6570e20962778001b479e4cc"
      ],
      "workouts": [
        {
          "id": 0.0633,
          "Distance": 1,
          "Lat": "100",
          "Long": "100",
          "speed": 60,
          "date": "100",
          "time": "1"
        }
      ],
      "userFriends":[{}]

    }
    

###
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
  "email": "TestingAdmin1@newpaltz.edu",
  "password": "12345678"
  
}

###
GET   http://localhost:3000/api/v1/users/search

Content-Type: application/json

{
  

 "email":"plotkinm@newpaltz.edu"
  
 }
  

